PUT http://localhost:5000/clientes
Content-Type: application/json

{
    "nome": "Maria",
    "email": "maria@gmail.com",
    "cpf": "15265932",
    "telefone": "698763235",
    "cep": "2598532",
    "bairro": "Alameda",
    "endereco": "Rua",
    "complemento": " ",
    "cidade": "São",
    "uf": "S"
}

###

GET http://localhost:5000/clientes/ok

### 

GET http://localhost:5000/clientes/not_ok

###

PUT http://localhost:5000/cobrancas
Content-Type: application/json

{
    "nome": "Cobrança Y",
    "descricao": "Cobrança Y",
    "vencimento": "2023/04/04",
    "valor": "3027",
    "status": "prevista",
    "cliente_id": "f6ff4b5f-6275-4ee3-a9cf-8c67d4a9b9d1"
}

### 

GET http://localhost:5000/cobrancas

###

GET http://localhost:5000/cobrancas/pagas

###

GET http://localhost:5000/cobrancas/previstas

###

GET http://localhost:5000/cobrancas/vencidas