PUT http://localhost:5000/cliente
Content-Type: application/json

{
    "nome": "Karol",
    "email": "karol@gmail.com",
    "cpf": "15265932",
    "telefone": "698763235",
    "cep": "2598532",
    "bairro": "Alameda",
    "endereco": "Rua",
    "complemento": " ",
    "cidade": "São",
    "uf": "S"
}

###

GET http://localhost:5000/cliente

###

GET http://localhost:5000/cliente/ok

### 

GET http://localhost:5000/cliente/not_ok

###

PUT http://localhost:5000/cobranca
Content-Type: application/json

{
    "nome": "detalhe",
    "descricao": "dksjdal",
    "vencimento": "2022/10/05",
    "valor": "5000",
    "status": "paga",
    "cliente_id": "b08a2a3b-6672-4e08-87a7-5e61e13fedd7"
}

### 

GET http://localhost:5000/cobranca

###

GET http://localhost:5000/cobranca/pagas

###

GET http://localhost:5000/cobranca/previstas

###

GET http://localhost:5000/cobranca/vencidas